name: Deploy Angular com Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOY_SERVER }} >> ~/.ssh/known_hosts

      - name: Deploy no servidor via SSH
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} << 'EOF'

            cd /home/kaue

            if [ ! -d "frontend" ]; then
              git clone https://github.com/CESIT-UEA/cloud-front-admin-tecnocomp.git frontend
            fi

            cd frontend

            git pull origin main

            docker stop frontend || true
            docker rm frontend || true

            docker rmi frontend || true

            docker build -t frontend .

            docker run -d -p 80:80 --name frontend frontend

          EOF